// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ideqbxjtaybejaatpcdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkZXFieGp0YXliZWphYXRwY2RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMjE4NDAsImV4cCI6MjA2MTg5Nzg0MH0.p0ugcKPkmqWPV0r1REq7itFlEVfWGq0ciFr4NmX9j0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);